//! Numerical parity against the PyTorch reference.
//!
//! Replays the fixed `(LAST, PERC)` input sequence (generated by
//! `tools/dump_reference.py`) through the Rust [`LossGen`] from a zero state and
//! asserts each logit matches the PyTorch output. This pins the GRU math, the
//! `[r; z; n]` weight layout, and the `perc` handling.

use super::LossGen;

#[path = "test_vectors.rs"]
mod test_vectors;
use test_vectors::{EXPECT_LOGIT, LAST, N, PERC};

#[test]
fn logits_match_pytorch_reference() {
    let mut model = LossGen::new();
    let mut max_err = 0.0f32;
    for i in 0..N {
        let logit = model.step(LAST[i], PERC[i]);
        let err = (logit - EXPECT_LOGIT[i]).abs();
        max_err = max_err.max(err);
        assert!(
            err < 1e-4,
            "step {i}: rust logit {logit} vs pytorch {} (|err| = {err})",
            EXPECT_LOGIT[i]
        );
    }
    eprintln!("max abs logit error over {N} steps: {max_err:e}");
}
