#!/usr/bin/env python3
"""Dump a reference logit sequence from the PyTorch LossGen, for the Rust
parity test (`src/model/parity_test.rs`).

Feeds a fixed, deterministic `(last, perc)` input sequence through the model
one step at a time (carrying GRU state, exactly like the streaming Rust port)
and records the raw output logits. The Rust test replays the same `LAST`/`PERC`
arrays from a zero state and asserts each logit matches within 1e-4 — proving
the hand-port's GRU math, weight layout, and perc handling are correct.

No RNG is involved, so the comparison is exact up to float precision.

    python3 tools/dump_reference.py
"""

from pathlib import Path

import torch
from torch import nn

ROOT = Path(__file__).resolve().parent.parent
CKPT = ROOT / "lossgen_2000.pth"
OUT = ROOT / "src" / "model" / "test_vectors.rs"


class LossGen(nn.Module):
    def __init__(self, gru1_size=8, gru2_size=16):
        super().__init__()
        self.gru1_size = gru1_size
        self.gru2_size = gru2_size
        self.dense_in = nn.Linear(2, 8)
        self.gru1 = nn.GRU(8, gru1_size, batch_first=True)
        self.gru2 = nn.GRU(gru1_size, gru2_size, batch_first=True)
        self.dense_out = nn.Linear(gru2_size, 1)

    def forward(self, loss, perc, states=None):
        if states is None:
            g1 = torch.zeros((1, loss.size(0), self.gru1_size))
            g2 = torch.zeros((1, loss.size(0), self.gru2_size))
        else:
            g1, g2 = states
        x = torch.tanh(self.dense_in(torch.cat([loss, perc], dim=-1)))
        o1, g1 = self.gru1(x, g1)
        o2, g2 = self.gru2(o1, g2)
        return self.dense_out(o2), [g1, g2]


def build_sequence():
    """Deterministic (last, perc) pairs exercising both inputs + state."""
    perc_cycle = [0.0, 0.05, 0.1, 0.2, 0.3, 0.5, 0.8, 1.0]
    last_seq, perc_seq = [], []
    for i in range(96):
        perc_seq.append(perc_cycle[i % len(perc_cycle)])
        # a fixed, non-trivial 0/1 pattern for the feedback input
        last_seq.append(1.0 if (i * 7 + 3) % 5 == 0 else 0.0)
    return last_seq, perc_seq


def fmt(x: float) -> str:
    return repr(float(x))


def main() -> None:
    ck = torch.load(CKPT, map_location="cpu")
    model = LossGen(**ck["model_kwargs"])
    model.load_state_dict(ck["state_dict"])
    model.eval()

    last_seq, perc_seq = build_sequence()
    logits = []
    states = None
    with torch.no_grad():
        for last_v, perc_v in zip(last_seq, perc_seq):
            last = torch.tensor([[[last_v]]], dtype=torch.float32)
            perc = torch.tensor([[[perc_v]]], dtype=torch.float32)
            out, states = model(last, perc, states)
            logits.append(out.item())

    n = len(logits)
    lines = [
        "// @generated by tools/dump_reference.py from lossgen_2000.pth",
        "// Reference logit sequence for the Rust parity test. DO NOT EDIT.",
        "#![cfg_attr(rustfmt, rustfmt::skip)]",
        "",
        f"pub const N: usize = {n};",
        f"pub const LAST: [f32; {n}] = [{', '.join(fmt(v) for v in last_seq)}];",
        f"pub const PERC: [f32; {n}] = [{', '.join(fmt(v) for v in perc_seq)}];",
        f"pub const EXPECT_LOGIT: [f32; {n}] = [{', '.join(fmt(v) for v in logits)}];",
        "",
    ]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({n} steps)")


if __name__ == "__main__":
    main()
