#!/usr/bin/env python3
"""Export the LossGen checkpoint into a generated Rust source file of
`const f32` arrays (`src/model/weights.rs`).

The plugin loads zero files at runtime: the weights live in the binary as
`const` arrays, so there is no allocation, parsing, or I/O on the audio thread.

Re-run this whenever `lossgen_2000.pth` changes:

    python3 tools/export_weights.py

Architecture (from the checkpoint + the LossGen module):
    dense_in : Linear(2 -> 8)            then tanh
    gru1     : GRU(8 -> 8)
    gru2     : GRU(8 -> 16)
    dense_out: Linear(16 -> 1)           raw logit (sigmoid applied outside)

PyTorch GRU weight layout: weight_ih_l0 / weight_hh_l0 rows are stacked as
[ r ; z ; n ] (reset, update, new), each of height `hidden_size`.
"""

from pathlib import Path

import torch

ROOT = Path(__file__).resolve().parent.parent
CKPT = ROOT / "lossgen_2000.pth"
OUT = ROOT / "src" / "model" / "weights.rs"


def fmt(x: float) -> str:
    # repr(float32->float) round-trips and always carries a '.' or 'e',
    # so the literal is unambiguously a float in a `[f32; N]` context.
    return repr(float(x))


def vec(name: str, t: torch.Tensor) -> str:
    n = t.numel()
    body = ", ".join(fmt(v) for v in t.flatten().tolist())
    return f"pub const {name}: [f32; {n}] = [{body}];\n"


def mat(name: str, t: torch.Tensor) -> str:
    rows, cols = t.shape
    lines = [f"pub const {name}: [[f32; {cols}]; {rows}] = ["]
    for r in range(rows):
        body = ", ".join(fmt(v) for v in t[r].tolist())
        lines.append(f"    [{body}],")
    lines.append("];\n")
    return "\n".join(lines)


def main() -> None:
    ckpt = torch.load(CKPT, map_location="cpu")
    sd = ckpt["state_dict"]
    kw = ckpt.get("model_kwargs", {})
    h1 = kw.get("gru1_size", 8)
    h2 = kw.get("gru2_size", 16)

    out = []
    out.append("// @generated by tools/export_weights.py from lossgen_2000.pth")
    out.append("// DO NOT EDIT BY HAND. Re-run the script to regenerate.")
    out.append("//")
    out.append("// PyTorch GRU gate row order in W_IH/W_HH/B_*: [ r ; z ; n ].")
    out.append("#![cfg_attr(rustfmt, rustfmt::skip)]")
    out.append("")
    out.append(f"pub const GRU1_SIZE: usize = {h1};")
    out.append(f"pub const GRU2_SIZE: usize = {h2};")
    out.append("")
    out.append(mat("DENSE_IN_W", sd["dense_in.weight"]))   # (8, 2)
    out.append(vec("DENSE_IN_B", sd["dense_in.bias"]))      # (8,)
    out.append(mat("GRU1_W_IH", sd["gru1.weight_ih_l0"]))   # (24, 8)
    out.append(mat("GRU1_W_HH", sd["gru1.weight_hh_l0"]))   # (24, 8)
    out.append(vec("GRU1_B_IH", sd["gru1.bias_ih_l0"]))     # (24,)
    out.append(vec("GRU1_B_HH", sd["gru1.bias_hh_l0"]))     # (24,)
    out.append(mat("GRU2_W_IH", sd["gru2.weight_ih_l0"]))   # (48, 8)
    out.append(mat("GRU2_W_HH", sd["gru2.weight_hh_l0"]))   # (48, 16)
    out.append(vec("GRU2_B_IH", sd["gru2.bias_ih_l0"]))     # (48,)
    out.append(vec("GRU2_B_HH", sd["gru2.bias_hh_l0"]))     # (48,)
    out.append(mat("DENSE_OUT_W", sd["dense_out.weight"]))  # (1, 16)
    out.append(vec("DENSE_OUT_B", sd["dense_out.bias"]))    # (1,)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out) + "\n")
    print(f"wrote {OUT} (gru1={h1}, gru2={h2})")


if __name__ == "__main__":
    main()
